services:

  db:
    build:
      dockerfile: Dockerfile
    container_name: postgres-container
    ports:
      - 6999:5432
    environment:
      - POSTGRES_DB=garage
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=test